#!/bin/bash

## Requires markdown-pdf (and npm, the Node.js package manager)
## npm install markdown-pdf

## To add a new glyph, add a new call to the list below

targetdir=$(pwd)

pushd ../../$1
markdown-pdf README.md --out $targetdir/$1.pdf
popd

