#!/bin/bash

## Requires markdown-pdf (and npm, the Node.js package manager)
## npm install markdown-pdf

## To add a new glyph, add a new call to the list below

function glyph_to_page {
    pushd ../../$1
    markdown-pdf README.md --out $targetdir/$1.pdf
    popd
    echo "\includepdf[pagecommand={}]{glyphscript/$1.pdf}" >> glyphs.tex
}


targetdir=$(pwd)
echo $targetdir

echo "% Autogenerated glyph page collection, do not edit by hand" > glyphs.tex

# list all glyphs here in the order they should be included
glyph_to_page Glyphs/assembly-scar
glyph_to_page blunt-restriction-site
glyph_to_page cds
glyph_to_page cleavage-site
glyph_to_page composite
glyph_to_page five-prime-overhang
glyph_to_page five-prime-sticky-restriction-site
glyph_to_page insulator
glyph_to_page no-glyph-assigned
glyph_to_page omitted-detail
glyph_to_page operator
glyph_to_page origin-of-replication
glyph_to_page primer-binding-site
glyph_to_page promoter
glyph_to_page ribosome-entry-site
glyph_to_page signature
glyph_to_page stability-element
glyph_to_page terminator
glyph_to_page unspecified
