#!/bin/bash

## Requires markdown-pdf (and npm, the Node.js package manager)
## npm install markdown-pdf

## To add a new glyph, add a new call to the list below

function glyph_to_page {
    pushd ../../$1
    markdown-pdf README.md --out $targetdir/$1.pdf
    popd
    echo "\includepdf[pagecommand={},pages={1-}]{glyphscript/$1.pdf}" >> glyphs.tex
}


targetdir=$(pwd)
#echo $targetdir

echo "% Autogenerated glyph page collection, do not edit by hand" > glyphs.tex

# list all glyphs here in the order they should be included
glyph_to_page Glyphs/aptamer
glyph_to_page Glyphs/assembly-scar
glyph_to_page Glyphs/blunt-restriction-site
glyph_to_page Glyphs/cds
glyph_to_page Glyphs/chromosomal-locus
glyph_to_page Glyphs/circular-plasmid
glyph_to_page Glyphs/cleavage-site
glyph_to_page Glyphs/composite
glyph_to_page Glyphs/engineered-region
glyph_to_page Glyphs/insulator
glyph_to_page Glyphs/intron
glyph_to_page Glyphs/no-glyph-assigned
glyph_to_page Glyphs/non-coding-rna
glyph_to_page Glyphs/omitted-detail
glyph_to_page Glyphs/operator
glyph_to_page Glyphs/origin-of-replication
glyph_to_page Glyphs/origin-of-transfer
glyph_to_page Glyphs/overhang
glyph_to_page Glyphs/polyA
glyph_to_page Glyphs/polypeptide-region
glyph_to_page Glyphs/primer-binding-site
glyph_to_page Glyphs/promoter
glyph_to_page Glyphs/ribosome-entry-site
glyph_to_page Glyphs/signature
glyph_to_page Glyphs/specific-recombination-site
glyph_to_page Glyphs/stability-element
glyph_to_page Glyphs/sticky-restriction-site
glyph_to_page Glyphs/stop-site
glyph_to_page Glyphs/terminator
glyph_to_page Glyphs/unspecified
