#!/bin/bash

## Requires markdown-pdf (and npm, the Node.js package manager)
## npm install markdown-pdf

## To add a new glyph, add a new call to the list below

function glyph_to_page {
    pushd ../../$1
    markdown-pdf README.md --out $targetdir/$1.pdf
    popd
    echo "\includepdf[pagecommand={},pages={1-}]{glyphscript/$1.pdf}" >> interactionnodeglyphs.tex
}


targetdir=$(pwd)
#echo $targetdir

echo "% Autogenerated glyph page collection, do not edit by hand" > interactionnodeglyphs.tex

# list all glyphs here in the order they should be included
glyph_to_page Glyphs/InteractionNodes/association
glyph_to_page Glyphs/InteractionNodes/dissociation
glyph_to_page Glyphs/InteractionNodes/process
