#!/bin/bash

## Requires markdown-pdf (and npm, the Node.js package manager)
## npm install markdown-pdf

## To add a new glyph, add a new call to the list below

function glyph_to_page {
    pushd ../../$1
    markdown-pdf README.md --out $targetdir/$1.pdf
    popd
    echo "\includepdf[pagecommand={},pages={1-}]{glyphscript/$1.pdf}" >> speciesglyphs.tex
}


targetdir=$(pwd)
#echo $targetdir

echo "% Autogenerated glyph page collection, do not edit by hand" > speciesglyphs.tex

# list all glyphs here in the order they should be included
glyph_to_page Glyphs/FunctionalComponents/complex
glyph_to_page Glyphs/FunctionalComponents/dsNA
glyph_to_page Glyphs/FunctionalComponents/macromolecule
glyph_to_page Glyphs/FunctionalComponents/no-glyph-assigned
glyph_to_page Glyphs/FunctionalComponents/protein
glyph_to_page Glyphs/FunctionalComponents/simple-chemical
glyph_to_page Glyphs/FunctionalComponents/ssNA
glyph_to_page Glyphs/FunctionalComponents/unspecified
