name: build_specification

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
        
      - name: Install dependencies
        run: |
          cd specification/glyphscript
          npm install markdown-pdf

      - name: Generate PDFs for glyphs
        run: python3 scripts/rebuild_glyphs.py
        
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@v0.2.0
        with:
          working_directory: specification
          root_file: sbolvisual.tex

      - name: Move PDF
        run: mkdir -p output && cp specification/sbolvisual.pdf output

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: PDF
          path: output

  build_sampler:
      runs-on: ubuntu-latest
      steps:
      - name: Set up Git repository
        uses: actions/checkout@v1

      - name: Install dependencies
        run: |
          sudo apt-get install libcairo2-dev build-essential python3-setuptools
          cd scripts
          pip3 install -r requirements.txt

      - name: Build samplers
        run: python3 scripts/generate_sampler.py

      - name: Upload samplers as artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: samplers
          path: sampler
